Models/Entrenador.cs
using System.Collections.Generic;

namespace entrenadores.Models
{
    public class Entrenador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        public Pueblo Pueblo { get; set; }
        public string Foto{ get; set; }

         // EF Shadow property
        public int PuebloId { get; set; }
        public ICollection<Entrenador> Entrenadores { get; set; }
       
    }
}

Models/EntrenadorContext.cs
using Microsoft.EntityFrameworkCore;

namespace entrenadores.Models
{
    public class EntrenadorContext : DbContext
    {
        public DbSet<Entrenador>  Entrenadores { get; set; }
        public DbSet<Pueblo> Pueblos { get; set; }

        public EntrenadorContext(DbContextOptions dco) : base(dco){
            
        }
    }
}

Models/ErrorViewModel.cs
using System;

namespace entrenadores.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pueblo.cs
using System.Collections.Generic;

namespace entrenadores.Models
{
    public class Pueblo
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public ICollection<Entrenador> Entrenadores { get; set; }

    }
}

Controllers/EntrenadorController.cs
using System.Linq;
using entrenadores.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace entrenadores.Controllers
{
    public class EntrenadorController : Controller
    {
        private readonly EntrenadorContext _context;

        public EntrenadorController(EntrenadorContext context) {
            _context = context;
        }
         public IActionResult Pueblos() {
             var pueblos = _context.Pueblos.Include(x => x.Entrenadores).OrderBy(e => e.Nombre).ToList();
             return View(pueblos);
         }
        public IActionResult Entrenadores() {
             var entrenadores = _context.Entrenadores.Include(x => x.Pueblo).OrderBy(e => e.Nombre).ToList();
             return View(entrenadores);
         }


         public IActionResult NuevoEntrenador() {
            ViewBag.Regiones = _context.Pueblos.ToList().Select(e => new SelectListItem(e.Nombre, e.Id.ToString()));
            return View();
        }
         [HttpPost]
        public IActionResult NuevoEntrenador(Entrenador e) {
            if (ModelState.IsValid) {
                _context.Add(e);
                _context.SaveChanges();
                return RedirectToAction("NuevoEntrenadorConfirmacion");
            }
            return View(e);
        }

        public IActionResult NuevoEntrenadorConfirmacion() {
            return View();
        }
        public IActionResult NuevoPueblo() {
            return View();
        }
         [HttpPost]
        public IActionResult NuevoPueblo(Pueblo e) {
            if (ModelState.IsValid) {
                _context.Add(e);
                _context.SaveChanges();
                return RedirectToAction("NuevoPuebloConfirmacion");
            }
            return View(e);
        }
        public IActionResult NuevoPuebloConfirmacion() {
            return View();
        }


        [HttpPost]
        public IActionResult BorrarPueblo(int id) {
            var pueblo = _context.Pueblos.Find(id);
            _context.Remove(pueblo);
            _context.SaveChanges();

            return RedirectToAction("Pueblos");
        }


        public IActionResult EditarPueblo(int id) {
            var pueblo = _context.Pueblos.Find(id);
            return View(pueblo);
        }

        [HttpPost]
        public IActionResult EditarPueblo(Pueblo e) {
            if (ModelState.IsValid) {
                var pueblo = _context.Pueblos.Find(e.Id);
                pueblo.Nombre = e.Nombre;
                _context.SaveChanges();
                return RedirectToAction("EditarPuebloConfirmacion");
            }
            return View(e);
        }

        public IActionResult EditarPuebloConfirmacion() {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using entrenadores.Models;

namespace entrenadores.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Entrenador/EditarPueblo.cshtml
@model Pueblo

<h1>Editar región</h1>

<form action="" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Editar</button>
</form>

Views/Entrenador/EditarPuebloConfirmacion.cshtml
<h1>Editar Pueblo</h1>

<p>El Pueblo fue editado con éxito</p>

Views/Entrenador/Entrenadores.cshtml
@model List<Entrenador>

 <h1>Lista de Entrenadores</h1>

<table class="table border">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Pueblo</th>
        <th>Foto</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Nombre</td>
            <td>@item.Pueblo</td>
            <td>
                @item.Foto</td>
            <td>
                <a href="/entrenadores/editarentrenador/@item.Id" class="btn btn-secondary">Editar</a>

                <form action="/entrenadores/borrarentrenador" method="post" class="d-inline-block">
                    <input type="hidden" name="id" value="@item.Id" />
                    <button class="btn btn-danger">Borrar</button>
                </form>
            </td>
        </tr>
    }
    @if (Model.Count == 0) {
        <tr>
            <td colspan="4" class="text-center">No se encontraron Entrenadores</td>
        </tr>
    }
</table>

<a href="/ubicaciones/nuevopueblo" class="btn btn-primary">Añadir Entrenador</a>   

Views/Entrenador/NuevoEntrenador.cshtml
@model Entrenador

<h1>Nuevo Entrenador</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Pueblo"></label>
        <select asp-for="PuebloId" asp-items="ViewBag.Pueblos" type="text" class="form-control"></select>
    </div>
    <div class="form-group">
        <label asp-for="Foto"></label>
        <input asp-for="Foto" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Entrenador/NuevoEntrenadorConfirmacion.cshtml
<h1>Nueva región</h1>

<p>La región fue creada con éxito</p>

Views/Entrenador/NuevoPueblo.cshtml
@model Pueblo

<h1>Nuevo Pueblo</h1>

<form action="" method="post">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" type="text" class="form-control">
    </div>
    <button class="btn btn-primary">Registrar</button>
</form>

Views/Entrenador/NuevoPuebloConfirmacion.cshtml
<h1>Nueva Pueblo</h1>

<p>El pueblo fue creado con éxito</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - entrenadores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">entrenadores</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entrenador" asp-action="NuevoPueblo">Nuevo Pueblo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entrenador" asp-action="NuevoEntrenador">Nuevo Entrenador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - entrenadores - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>